### ISSUE TITLE
[BUG] Tronxy X5SA build error and fix

### ISSUE THREAD

**Issue by Links2004** [MarlinFirmware/Configurations#381]
current  `import-2.0.x`  commit does not build with `2.0.x` from Marlin
for Tronxy X5SA

error:
```
In file included from Marlin/src/module/../inc/MarlinConfig.h:47:0,
                 from Marlin/src/module/motion.h:31,
                 from Marlin/src/module/motion.cpp:27:
Marlin/src/module/motion.cpp:151:16: error: 'HOMING_FEEDRATE_XY' was not declared in this scope
     MMM_TO_MMS(HOMING_FEEDRATE_XY), MMM_TO_MMS(HOMING_FEEDRATE_XY),
                ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:151:16: note: suggested alternative: 'HOMING_FEEDRATE_MM_M'
     MMM_TO_MMS(HOMING_FEEDRATE_XY), MMM_TO_MMS(HOMING_FEEDRATE_XY),
                ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:151:48: error: 'HOMING_FEEDRATE_XY' was not declared in this scope
     MMM_TO_MMS(HOMING_FEEDRATE_XY), MMM_TO_MMS(HOMING_FEEDRATE_XY),
                                                ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:151:48: note: suggested alternative: 'HOMING_FEEDRATE_MM_M'
     MMM_TO_MMS(HOMING_FEEDRATE_XY), MMM_TO_MMS(HOMING_FEEDRATE_XY),
                                                ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:153:14: error: 'HOMING_FEEDRATE_Z' was not declared in this scope
   MMM_TO_MMS(HOMING_FEEDRATE_Z)
              ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:153:14: note: suggested alternative: 'HOMING_FEEDRATE_MM_M'
   MMM_TO_MMS(HOMING_FEEDRATE_Z)
              ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
*** [.pio/build/chitu_f103/src/src/module/motion.cpp.o] Error 1
```

fixed via:

```diff
diff --git a/Marlin/Configuration.h b/Marlin/Configuration.h
index 339065233a..53d2d4adfb 100644
--- a/Marlin/Configuration.h
+++ b/Marlin/Configuration.h
@@ -1500,7 +1504,11 @@
 #endif
 
 // Homing speeds (mm/min)
-#define HOMING_FEEDRATE_MM_M { (50*60), (50*60), (4*60) }
+#define HOMING_FEEDRATE_XY (50*60)
+#define HOMING_FEEDRATE_Z  (4*60)
+
+// Homing speeds (mm/min)
+#define HOMING_FEEDRATE_MM_M { HOMING_FEEDRATE_XY, HOMING_FEEDRATE_XY, HOMING_FEEDRATE_Z }
 
 // Validate that endstops are triggered on homing moves
 #define VALIDATE_HOMING_ENDSTOPS
```

**Comment by sjasonsmith** [comment]
The import_2.0.x branch is only for incoming changes. Switch to the branch which matches the Marlin release you are using.
