### PR TITLE
Remove HOMING_FEEDRATE_XY/Z defines

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

This PR catches up current configs to remove HOMING_FEEDRATE_XY/Z references.

Note: The ET5 configs were not updated here since that is being handled in # 373

### Benefits

Remove invalid references.

### Related Issues

None. Found while cleaning up the ET4/5 configs in my other PR.

### CODE REVIEW

**Comment by alfonder** [comment]
@thisiskeithb these commits break building Marlin from branch "2.0.x" .
As to my knowledge, Configurations branch "import-2.0.x" should correspond to Marlin branch "2.0.x", and Configurations branch "bugfix-2.0.x" should match Marlin branch "bugfix-2.0.x".
But for now several commits in Configurations (branch "import-2.0.x") have no corresponding merges to Marlin branch "2.0.x". Therefore image building fails on top of the branches "2.0.x" - "import-2.0.x". I think, this situation needs to be fixed.

**Comment by alfonder** [comment]
Here is the error itself:
<details><summary>Build Output</summary>

```
Compiling .pio/build/STM32F103RE_btt_USB/src/src/module/temperature.cpp.o
In file included from Marlin/src/module/../inc/MarlinConfig.h:47:0,
                 from Marlin/src/module/motion.h:31,
                 from Marlin/src/module/motion.cpp:27:
Marlin/src/module/motion.cpp:151:16: error: 'HOMING_FEEDRATE_XY' was not declared in this scope
     MMM_TO_MMS(HOMING_FEEDRATE_XY), MMM_TO_MMS(HOMING_FEEDRATE_XY),
                ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:151:16: note: suggested alternative: 'HOMING_FEEDRATE_MM_M'
     MMM_TO_MMS(HOMING_FEEDRATE_XY), MMM_TO_MMS(HOMING_FEEDRATE_XY),
                ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:151:48: error: 'HOMING_FEEDRATE_XY' was not declared in this scope
     MMM_TO_MMS(HOMING_FEEDRATE_XY), MMM_TO_MMS(HOMING_FEEDRATE_XY),
                                                ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:151:48: note: suggested alternative: 'HOMING_FEEDRATE_MM_M'
     MMM_TO_MMS(HOMING_FEEDRATE_XY), MMM_TO_MMS(HOMING_FEEDRATE_XY),
                                                ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:153:14: error: 'HOMING_FEEDRATE_Z' was not declared in this scope
   MMM_TO_MMS(HOMING_FEEDRATE_Z)
              ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp:153:14: note: suggested alternative: 'HOMING_FEEDRATE_MM_M'
   MMM_TO_MMS(HOMING_FEEDRATE_Z)
              ^
Marlin/src/module/../inc/../core/types.h:76:43: note: in definition of macro 'MMM_TO_MMS'
 #define MMM_TO_MMS(MM_M) feedRate_t(float(MM_M) / 60.0f)
                                           ^~~~
Marlin/src/module/motion.cpp: In function 'void do_z_clearance(const float&, bool, bool, bool)':
Marlin/src/module/motion.cpp:513:100: error: 'HOMING_FEEDRATE_Z' was not declared in this scope
```
</details>

**Comment by ellensp** [comment]
@alfonder "As to my knowledge, Configurations branch "import-2.0.x" should correspond to Marlin branch "2.0.x"" this is not correct.  from the readme of the repository
Branches
Release: For most Marlin users. Select the version that matches the Marlin version you are compiling.
Bugfix: For users compiling the bugfix branch of Marlin.
Import: For developers maintaining the Configuration examples.

2.0.x is always the latest release, + a few important patches. it uses latest release config examples.

**Comment by alfonder** [comment]
@ellensp so what Marlin branch should build with Configurations "import-2.0.x" ?

**Comment by ellensp** [comment]
Additionally If you look in the config directory of the Marlin you downloaded you will find a readme that tells you what version of config files to get eg https://github.com/MarlinFirmware/Marlin/tree/2.0.x/config

You do not use import for any version of marlin, it is used to generate all other config versions.
It is for developers to add new Configuration examples to.

**Comment by alfonder** [comment]
@ellensp come on, if I downloaded Marlin as archive there would not be a question "how to get configuration". But when I want to create a PR to Configuration "import-2.0.x", I should test my changes. So it should be a corresponding branch of Marlin to **checkout** (not download).
Last time (September '20) it was branch "2.0.x" of Marlin. Now I couldn't find any.

**Comment by ellensp** [comment]
All updates are done against bugfix branch, this includes config files.
Once you have tested them on bugfix , you then create a PR against Import to have them added to the collection.

**Comment by alfonder** [comment]
Thanks.
