### PR TITLE
Update documentation for TINA2 models

### PR DESCRIPTION
**Pull request by czlr**
### Description

Documentation update only, no code changes.
Updates the documentation for TINA2 to better explain the differences in the models. The firmware between them needs to be configured differently, but unfortunately results/discussions online often lump them all together. E.g., if searching "tina2 firmware upgrade". Which also caused me a lot of headaches before realizing.

### Benefits

People using one of the TINA2 printers (who are often beginners) can now realize there are different models, and configure things accordingly.

I'm also working on a V7 2.1.x config for my own printer. If I figure it out, I can contribute it with another MR.

### Related Issues

N/A

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Related to this, I built all of our hosted configurations last night and found the Tina2 configs do not build:

### Weedo/Tina2/V2/
<details><summary>PREHEAT_2_TEMP_HOTEND (240) must be less than HEATER_0_MAXTEMP (240) - 15:</summary>
<p>

```prolog
Getting configuration files from ./.pio/build-import-2.1.x/config/examples/Weedo/Tina2/V2/
Building the firmware now...
/.platformio/penv/bin/pio

Auto Build...
Building environment mega2560 for board WEEDO_62A (1330)...

In file included from Marlin/src/module/../inc/MarlinConfigPre.h:37:0,
                 from Marlin/src/module/../inc/MarlinConfig.h:28,
                 from Marlin/src/module/../MarlinCore.h:24,
                 from Marlin/src/module/temperature.cpp:30:
Marlin/src/module/temperature.cpp:310:38: error: static assertion failed: PREHEAT_2_TEMP_HOTEND (240) must be less than HEATER_0_MAXTEMP (240) - 15.
     #define CHECK_PREHEAT__(N,P,T,M) static_assert(T <= (M) - (HOTEND_OVERSHOOT), "PREHEAT_" STRINGIFY(P) "_TEMP_HOTEND (" STRINGIFY(T) ") must be less than HEATER_" STRINGIFY(N) "_MAXTEMP (" STRINGIFY(M) ") - " STRINGIFY(HOTEND_OVERSHOOT) ".");
                                      ^
[snip]
*** [.pio/build/mega2560/src/src/module/temperature.cpp.o] Error 1
================================================ [FAILED] Took 15.07 seconds ================================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:15.072
=========================================== 1 failed, 0 succeeded in 00:00:15.072 ===========================================
Failed
```
</p>
</details>

### Weedo/Tina2/V3/
<details><summary>PREHEAT_2_TEMP_HOTEND (240) must be less than HEATER_0_MAXTEMP (240) - 15:</summary>
<p>

```prolog
Getting configuration files from ./.pio/build-import-2.1.x/config/examples/Weedo/Tina2/V3/
Building the firmware now...
/.platformio/penv/bin/pio

Auto Build...
Building environment mega2560 for board WEEDO_62A (1330)...

In file included from Marlin/src/module/../inc/MarlinConfigPre.h:37:0,
                 from Marlin/src/module/../inc/MarlinConfig.h:28,
                 from Marlin/src/module/../MarlinCore.h:24,
                 from Marlin/src/module/temperature.cpp:30:
Marlin/src/module/temperature.cpp:310:38: error: static assertion failed: PREHEAT_2_TEMP_HOTEND (240) must be less than HEATER_0_MAXTEMP (240) - 15.
     #define CHECK_PREHEAT__(N,P,T,M) static_assert(T <= (M) - (HOTEND_OVERSHOOT), "PREHEAT_" STRINGIFY(P) "_TEMP_HOTEND (" STRINGIFY(T) ") must be less than HEATER_" STRINGIFY(N) "_MAXTEMP (" STRINGIFY(M) ") - " STRINGIFY(HOTEND_OVERSHOOT) ".");
                                      ^
[snip]
*** [.pio/build/mega2560/src/src/module/temperature.cpp.o] Error 1
================================================ [FAILED] Took 15.12 seconds ================================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:00:15.122
=========================================== 1 failed, 0 succeeded in 00:00:15.122 ===========================================
Failed
```
</p>
</details>

I'll probably end up dropping the `PREHEAT_2_*` / ABS option for these configs since the max hotend temp is 225.

**Comment by jarno83** [comment]
> ### Description
> Documentation update only, no code changes. Updates the documentation for TINA2 to better explain the differences in the models. The firmware between them needs to be configured differently, but unfortunately results/discussions online often lump them all together. E.g., if searching "tina2 firmware upgrade". Which also caused me a lot of headaches before realizing.
> 
> ### Benefits
> People using one of the TINA2 printers (who are often beginners) can now realize there are different models, and configure things accordingly.
> 
> I'm also working on a V7 2.1.x config for my own printer. If I figure it out, I can contribute it with another MR.
> 
> ### Related Issues
> N/A

Hi, have you hade any progres with V7 configs? Thanks.

**Comment by czlr** [comment]
> Hi, have you hade any progres with V7 configs? Thanks.

Sorry for the late reply. Sort of... yes and no. I've stopped looking into it, but these are my notes:

The main issue is that the TINA2 firmware requires other substantial code changes to work. If I'm understanding the philosophy here, having a clean config would be meaningless in the spirit of things if it can't be simply dropped into marlin to get a working build. Studying their reference Marlin 2.0.x firmware, they've added a bunch of custom files, along with small inline edits to the marlin sources scattered throughout. But most of it relates to their custom LCD display: https://github.com/weedo3d/Tina2Upgradefirmware/tree/main/Marlin/src/wtlib. 

Code/feature stuff to call out in their reference 2.0.x firmware (https://github.com/weedo3d/Tina2Upgradefirmware):
- Has custom nozzle z offset adjustment. Requires EEPROM related flags enabled in `configuration.h`
- Has custom SD card menu for selecting print files. It shows basic metadata like expected print time, temperature, etc. by parsing custom gcode header comments.
- Seems there's also an undocumented TINA2 V5, where a user on reddit receieved a firmware named `TINA2V5_WEEDO_BASIC_V1.0.7.wfm`. https://www.reddit.com/r/3Dprinting/comments/100rxft/completely_blank_screen_after_attempting_firmware/
- `#define NOZZLE_TO_PROBE_OFFSET { 0, 0, 0 }` in `configuration.h` is left unconfigured. If I understand correctly, this will cause a slight shift in the bed leveling mesh?
- Under their current code, LCD bed leveling is just broken because they directly attempt G29 after G28 without re-enabling it. The repo code doesn't yet contain `ENABLE_LEVELING_AFTER_G28`. And they aren't doing `RESTORE_LEVELING_AFTER_G28` with `M420 S` either. https://marlinfw.org/docs/gcode/G028.html, https://github.com/weedo3d/Tina2Upgradefirmware/blob/main/Marlin/src/lcd/ultralcd.cpp#L2345
