### ISSUE TITLE
Compilation Error on Unchanged Ender 5 Example Config 

### ISSUE THREAD

**Issue by jmb-555** [MarlinFirmware/Configurations#899]
### Bug Description

Default config file for ender 5 does not compile for Bigtreetech Mini SKR E3 V2

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.
[Configurations.zip](https://github.com/MarlinFirmware/Configurations/files/10787561/Configurations.zip)

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. Download latest marlin.
2. Swap configuration files out for the example on for Mini SKR V2
3. Comple with VS Code
4. Error and compilation unsuccessful

**Expected behavior:**

**Actual behavior:**

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md) for additional guidelines.

**Comment by thisiskeithb** [comment]
You're using configs from an import branch which include intentional `#error` lines to prevent compilation since they're only meant to be used to build other branches:

```cpp
#error "Don't build with import-2.1.x configurations!"
#error "Use the 'bugfix...' or 'release...' configurations matching your Marlin version."
```

Use the [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x) or one of the release branches ([`release-2.1.2`](https://github.com/MarlinFirmware/Configurations/archive/refs/heads/release-2.1.2.zip) is the latest as of this comment) instead.
