### PR TITLE
initial add of Ender 3 max neo

### PR DESCRIPTION
**Pull request by ellensp**
### Description

First run at at configs for Ender 3 max neo

### Benefits

We have a config

### Related Issues
https://github.com/MarlinFirmware/Configurations/issues/649#issuecomment-1646279257

### Note
I do not have access to this machine.
Is configured from a M503 Dump of Ender 3 max neo firmware on a stock 4.2.2 + information on the internet
<details><summary>M503 of creality provided firmware</summary>
<p>

```
> echo:  G21    ; Units in mm (mm)
> echo:; Filament settings: Disabled
> echo:  M200 S0 D1.75
> echo:; Steps per unit:
> echo: M92 X80.08 Y80.17 Z400.00 E101.30
> echo:; Maximum feedrates (units/s):
> echo:  M203 X180.00 Y180.00 Z5.00 E25.00
> echo:; Maximum Acceleration (units/s2):
> echo:  M201 X500.00 Y500.00 Z50.00 E1000.00
> echo:; Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
> echo:  M204 P500.00 R800.00 T1000.00
> echo:; Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
> echo:  M205 B20000.00 S0.00 T0.00 X5.00 Y5.00 Z0.30 E5.00
> echo:; Home offset:
> echo:  M206 X0.00 Y0.00 Z0.00
> echo:; Auto Bed Leveling:
> echo:  M420 S0 Z10.00
> echo:; Material heatup parameters:
> echo:  M145 S0 H200.00 B60.00 F255
> echo:  M145 S1 H240.00 B100.00 F255
> echo:; PID settings:
> echo:  M301 P12.72 I0.79 D51.23
> echo:  M304 P198.96 I38.80 D680.25
> echo:; Power-Loss Recovery:
> echo:  M413 S1
> echo:; Z-Probe Offset (mm):
> echo:  M851 X-57.00 Y-20.00 Z0.00
> echo:; Filament load/unload lengths:
> echo:  M603 L0.00 U100.00
```
</p>
</details>

IT HAS NOT BEEN TESTED, beyond compiling

From internet descriptions and creality provided firmware it has either a DACAI or a VIEWE Clone E3V2 display

### CODE REVIEW

**Comment by Kuinox** [comment]
Do you know which one I should build ?
image
Is there a danger to to flash the wrong firmware on my 3D printer ?

**Comment by ellensp** [comment]
You need to identify which chip you have on your controller  A STM32F103RE or a STM32F103RC

Then the first one of that type.

define danger...   if you just hit print without doing the basic testing, you might damage your printer

**Comment by Kuinox** [comment]
Mhhh, I found a GD32F303RET6
To see further than that I need to disconnect everything...

**Comment by ellensp** [comment]
That is a problem then...  GD chips not being supported in official Marlin

**Comment by Kuinox** [comment]
Should I keep looking or there will be only this microcontroller on the board ?

**Comment by ellensp** [comment]
Creality V4.2.2 boards come with 1 of 4 different MPU's

STM32F103RC   <- Supported
STM32F103RE   <- Supported
GD32F103RE
GD32F303RE

What you get is random...  

Basically at this time you are limited to creality provided firmware

**Comment by Kuinox** [comment]
> Basically at this time you are limited to creality provided firmware

Thanks, good to know, looks like I will have to shop another motherboard...

I managed to build the firmware once, but now I have this error:  
```
c:\dev\marlin\marlin\configuration.h:23:2: error: #error "Don't build with import-2.1.x configurations!"
   23 | #error "Don't build with import-2.1.x configurations!"
      |  ^~~~~
```

**Comment by ellensp** [comment]
When testing import branch Configs on latest bugfix2.1.x you must comment out 

```
#error "Don't build with import-2.1.x configurations!"
#error "Use the 'bugfix...' or 'release...' configurations matching your Marlin version."

```
From Configuration.h

**Comment by Kuinox** [comment]
By following a ritual I managed to make it work.  
Homing works, z homing with bltouch works, temperature reports works.
What kind of tests do you want I run ?

**Comment by Kuinox** [comment]
I tried to print a calibration cube after bed leveling.  
I think the config miss all the offsets. 
It looks like the config assume the buttons are aligned with the bed/printer head, but it's not.

**Comment by ellensp** [comment]
That is something I cannot determine from old firmware, measure the offsets
Home X, measure distance from home to X0 position over the bed, for eg say it reads 5mm
Home Y, measure distance from home to Y0 position over the bed, for eg say it reads 7 mm

In Configuration.h set
#define X_MIN_POS -5
#define Y_MIN_POS -7

Please advise on real numbers so I can update this example config

**Comment by Kuinox** [comment]
I don't have access to my printer until later today, but I just found a marlin config for this printer on github:  
https://github.com/TheMDev/Ender_3_Max_Neo_4.2.2_Firmware/blob/master/autogeneratedConfigs/default/nightly/0e2c5b45ece8ebe591e27cebe9570f9049a55f83/Configuration.h#L1764
Also have probe height: 
https://github.com/TheMDev/Ender_3_Max_Neo_4.2.2_Firmware/blob/master/autogeneratedConfigs/default/nightly/0e2c5b45ece8ebe591e27cebe9570f9049a55f83/Configuration.h#L1416

**Comment by ellensp** [comment]
Some of that config is clearly "not right"  

I have  added the bed X and Y offsets, but the probe height is for a  different type of probe  
And a few other minor changes see https://github.com/MarlinFirmware/Configurations/pull/961/commits/0388ba8af30af40a199154eac0034537c54ef081

for example that config says #define NOZZLE_TO_PROBE_OFFSET { -40, -12, 0 } 
but the creality firmware says 

> echo:; Z-Probe Offset (mm):
> echo:  M851 X-57.00 Y-20.00 Z0.00

Im inclined to believe the firmware, until someone actually measures it.

**Comment by Kuinox** [comment]
For the offsets I will try to load the original firmware and see at which value are the buttons.

**Comment by Kuinox** [comment]
I checked on my end, the X&Y offsets are now the same than what the crealty firmware display on screen.  
There is no Z offset, it's set manually from the screen.  
> Im inclined to believe the firmware, until someone actually measures it.  

I'll try this evening.

**Comment by Kuinox** [comment]
> until someone actually measures it.

So I measured the offset nozzle to probe.  
The probe is x:-3.6cm and y:-1.2cm relative to the nozzle.  
It looks like the config is more correct than the firmware.  
There is also a slight z offset that I need other tool than a sheet of milimetric paper to measure.  

This offset is normally corrected by a manually inputed z offset on the screen.

**Comment by Kuinox** [comment]
Is there something to be done for the screen support ?

**Comment by thinkyhead** [comment]
> Is there something to be done for the screen support ?

Is it something other than the `DWIN_CREALITY_LCD`? If this is one of the same displays they ship with the Ender-3 V2 then you just need to follow the instructions [here](https://github.com/MarlinFirmware/Configurations/blob/bugfix-2.1.x/config/examples/Creality/Ender-3%20V2/README.md) to update the display assets.

If this works (or doesn't) then it might help just to add a `README.md` like the one in the `Ender-3 V2` config folder.
